spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-master: # 主数据源
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: 
        url: jdbc:mysql://ip:3306/master_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      test-slave: # 从数据源
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: 
        url: jdbc:mysql://ip:3306/slave_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
mybatis:
  mapper-locations: classpath:mapper/*.xml
